// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjmx8DWRF9wI5psY_SG95ObPd2zp4F6NY',
    appId: '1:282781447307:web:2f9514d252dc8a36fc508e',
    messagingSenderId: '282781447307',
    projectId: 'oilerpmobile',
    authDomain: 'oilerpmobile.firebaseapp.com',
    storageBucket: 'oilerpmobile.firebasestorage.app',
    measurementId: 'G-YTVT4MYCZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHNTcnbduuD4Cg_WqgxvlqJh11rrXVb4o',
    appId: '1:282781447307:android:70487f4e8a9bccc5fc508e',
    messagingSenderId: '282781447307',
    projectId: 'oilerpmobile',
    storageBucket: 'oilerpmobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGm2KD8yGidCwjPy_25OUzAcYXqQYXNeo',
    appId: '1:282781447307:ios:f2fc4dd13bdda31bfc508e',
    messagingSenderId: '282781447307',
    projectId: 'oilerpmobile',
    storageBucket: 'oilerpmobile.firebasestorage.app',
    iosBundleId: 'com.example.oilErp',
  );

}